quotes_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "quotes_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('quotes/', views.quotes, name='quotes'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('<int:pk>/edit/', views.AuthorUpdateView.as_view(), name='author_update'),
    path('<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

quotes_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_app.urls')),

]

quotes_app/models.py
# quotes/models.py (PostgreSQL models)
from django.contrib.auth.models import User
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=255)
    born_date = models.CharField(max_length=255, blank=True, null=True)
    born_location = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.fullname

class Quote(models.Model):
    tags = models.JSONField(default=list)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()

    def __str__(self):
        return self.quote

quotes_app/forms.py
from django import forms
from .models import Author, Quote
#для юзеров
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    pass

quotes_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Author, Quote
from .forms import AuthorForm, QuoteForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, LoginForm


def index(request):
    return render(request, 'index.html')


def authors(request):
    authors = Author.objects.all()
    return render(request, 'authors.html', {'authors': authors})


def quotes(request):
    quotes = Quote.objects.all()
    return render(request, 'quotes.html', {'quotes': quotes})

#функциональное представление
@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authors')
    else:
        form = AuthorForm()
    return render(request, 'add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes')
    else:
        form = QuoteForm()
    return render(request, 'add_quote.html', {'form': form})


#классовое представление
class AuthorUpdateView(LoginRequiredMixin, UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'author_update.html'
    success_url = '/authors/'


class AuthorDetailView(LoginRequiredMixin, DetailView):
    model = Author
    template_name = 'author_detail.html'


# функциональное представление
def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)  # Автоматический вход после регистрации
            return redirect('quotes_app:index')  # Перенаправление на домашнюю страницу
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form})


# функциональное представление
def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('quotes_app:index')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


@login_required
def logout(request):
    auth_logout(request)
    return redirect('quotes_app:index')

quotes_app/templates/add_author.html
{% extends "base.html" %}

{% block content %}
    <h1>Add New Author</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Add Author</button>
    </form>
{% endblock %}

quotes_app/templates/add_quote.html
{% extends "base.html" %}

{% block content %}
    <h1>Add New Quote</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Add Quote</button>
    </form>
{% endblock %}

quotes_app/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ author.fullname }}</h1>
    <p><strong>Born Date:</strong> {{ author.born_date }}</p>
    <p><strong>Born Location:</strong> {{ author.born_location }}</p>
    <p><strong>Description:</strong> {{ author.description }}</p>
    <p><a href="{% url 'quotes_app:author_update' author.id %}">Edit</a></p>
    <p><a href="{% url 'quotes_app:authors' %}">Back to Author List</a></p>
{% endblock %}

quotes_app/templates/author_update.html
{% extends "base.html" %}

{% block content %}
    <h1>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Author</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

quotes_app/templates/authors.html
{% extends "base.html" %}

{% block content %}
    <h1>Authors</h1>
    <section>
        <!-- Удален второй заголовок <h2>Authors</h2> -->
        <table>
            <thead>
                <tr>
                    <th>Full Name</th>
                    <!-- <th>Born Date</th> -->
                    <!-- <th>Born Location</th> -->
                    <!-- <th>Description</th> -->
                    <!-- <th>Actions</th> -->
                </tr>
            </thead>
            <tbody>
                {% for author in authors %}
                <tr>
                    <td>{{ author.fullname }}</td>
                    <!-- <td>{{ author.born_date }}</td> -->
                    <!-- <td>{{ author.born_location }}</td> -->
                    <!-- <td>{{ author.description }}</td> -->
                    <td>
                        <a href="{% url 'quotes_app:author_detail' author.id %}" role="button" class="secondary">View</a>
                        <a href="{% url 'quotes_app:author_update' author.id %}" role="button" class="secondary">Edit</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No authors available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Ссылка на форму добавления автора -->
        <p>
            <a href="{% url 'quotes_app:add_author' %}" role="button" class="secondary">Add New Author</a>
        </p>
    </section>
{% endblock %}

quotes_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<main class="container">
    <nav>
        <a href="{% url 'quotes_app:index' %}">Home</a>
<!--        <a href="{% url 'quotes_app:authors' %}">Authors</a>-->
<!--        <a href="{% url 'quotes_app:quotes' %}">Quotes</a>-->
        {% if user.is_authenticated %}
            <a href="{% url 'quotes_app:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'quotes_app:login' %}">Login</a>
            <a href="{% url 'quotes_app:register' %}">Register</a>
        {% endif %}
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes_app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1 class="page-title">Welcome to the Quotes Archive</h1>

    <section class="intro">
        <p>Explore our collection of authors and their quotes. Click on the links below to see more details.</p>
    </section>

    <section class="navigation">
        <h2>Navigate</h2>
        <div class="nav-buttons">
            <a href="{% url 'quotes_app:authors' %}" class="btn">View Authors</a>
            <a href="{% url 'quotes_app:quotes' %}" class="btn">View Quotes</a>
        </div>
    </section>

    <style>
        .intro {
            text-align: center;
            margin-bottom: 20px;
        }

        .navigation {
            text-align: center;
            margin-bottom: 30px;
        }

        .nav-buttons {
            display: flex;
            justify-content: center;
            gap: 20px;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            color: #fff;
            background-color: #007BFF;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .btn:hover {
            background-color: #0056b3;
        }
         .page-title {
            text-align: center;
            margin-bottom: 20px;
        }
    </style>
{% endblock %}

quotes_app/templates/login.html
{% extends "base.html" %}

{% block content %}
  <h2>Вход</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
  </form>
  <p><a href="{% url 'quotes_app:password_reset' %}">Забыли пароль?</a></p>

{% endblock %}

quotes_app/templates/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
  <h2>Пароль успешно сброшен</h2>
  <p>Ваш пароль был успешно обновлен. Вы можете войти в систему, используя новый пароль.</p>
{% endblock %}

quotes_app/templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
  <h2>Введите новый пароль</h2>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="new_password1">Новый пароль:</label>
      <input type="password" name="new_password1" required>
    </div>
    <div>
      <label for="new_password2">Повторите новый пароль:</label>
      <input type="password" name="new_password2" required>
    </div>
    <button type="submit">Сбросить пароль</button>
  </form>
{% endblock %}
4. password_reset_complete.html
html
Копировать код
{% extends "base_generic.html" %}

{% block content %}
  <h2>Пароль успешно сброшен</h2>
  <p>Ваш пароль был успешно обновлен. Вы можете войти в систему, используя новый пароль.</p>
{% endblock %}

quotes_app/templates/password_reset_done.html
{% extends "base.html" %}

{% block content %}
  <h2>Инструкции по сбросу пароля отправлены</h2>
  <p>На указанный адрес электронной почты были отправлены инструкции по сбросу пароля.</p>
  <p>Проверьте свою почту!</p>
{% endblock %}

quotes_app/templates/password_reset_form.html
{% extends "base.html" %}

{% block content %}
  <h2>Сброс пароля</h2>
  <form method="post">
    {% csrf_token %}
    <p>Введите ваш адрес электронной почты, чтобы получить инструкции по сбросу пароля:</p>
    <div>
      <label for="email">Электронная почта:</label>
      <input type="email" name="email" required>
    </div>
    <button type="submit">Отправить</button>
  </form>
{% endblock %}

quotes_app/templates/quotes.html
{% extends "base.html" %}

{% block content %}
    <h1>Quotes</h1>
    <section style="margin-top: 30px;">
        <!-- Удален второй заголовок <h2>Quotes</h2> -->
        <table>
            <thead>
                <tr>
                    <th>Quote</th>
                    <th>Tags</th>
                    <th>Author</th>
                </tr>
            </thead>
            <tbody>
                {% for quote in quotes %}
                <tr>
                    <td>{{ quote.quote }}</td>
                    <td>
                        {% for tag in quote.tags %}
                            {{ tag }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ quote.author.fullname }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">No quotes available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Ссылка на форму добавления цитаты -->
        <p>
            <a href="{% url 'quotes_app:add_quote' %}" role="button" class="secondary">Add New Quote</a>
        </p>
    </section>
{% endblock %}

quotes_app/templates/register.html
{% extends "base.html" %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}